services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web_development
    command: uv run manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
        - action: sync+restart
          path: uv.lock
          target: /app/uv.lock
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
      - CELERY_BROKER_URL=redis://cache:6379/0
      - AWS_S3_ENDPOINT_URL=http://storage:9000
    restart: on-failure
  database:
    image: postgres:18-alpine3.22
    environment:
      POSTGRES_DB: lulzcasz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: on-failure
  cache:
    image: redis:8.0-alpine3.21
    ports:
      - 6379:6379
    command: redis-server
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker_development
    command: uv run celery -A lulzcasz worker --loglevel=INFO --concurrency=2
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
        - action: sync+restart
          path: uv.lock
          target: /app/uv.lock
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
      - CELERY_BROKER_URL=redis://cache:6379/0
      - AWS_S3_ENDPOINT_URL=http://storage:9000
      - AWS_S3_CUSTOM_DOMAIN=storage:9000/lulzcasz
    restart: on-failure
  storage:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
