[project]
name = "laboratoriodolyc-com-br"
version = "0.0.0"
description = "laboratoriodolyc.com.br source code"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "django~=5.2",
]

[dependency-groups]
dev = [
    "psycopg[binary]~=3.2",
    "rust-just~=1.43",
]
